scrum/urls.py
from django.conf.urls import patterns, url

from scrum.views import (BugView, CheckRecentUpdates, CreateBZProductView,
                         CreateProjectView, CreateSprintView, CreateTeamView,
                         DeleteBZProductView, EditProjectView, EditSprintView,
                         EditTeamView, ListProjectsView, ListTeamsView,
                         ManageProjectBugsView, ManageSprintBugsView,
                         ProjectView, ProjectBacklogView, RedirectOldURLsView,
                         SprintView, TeamView)


urlpatterns = patterns(
    '',
    url(r'^b/(?P<pk>\d+)/$', BugView.as_view(), name='scrum_bug'),
    url(r'^p/$', ListProjectsView.as_view(), name='scrum_projects_list'),
    url(r'^t/$', ListTeamsView.as_view(), name='scrum_teams_list'),
    url(r'^p/new/$', CreateProjectView.as_view(), name='scrum_project_new'),
    url(r'^t/new/$', CreateTeamView.as_view(), name='scrum_team_new'),
    url(r'^p/product/(?P<pk>\d+)/delete/$', DeleteBZProductView.as_view(),
        name='scrum_product_delete'),
    url(r'^p/(?P<slug>[-\w\.]+)/$', ProjectView.as_view(),
        name='scrum_project'),
    url(r'^t/(?P<slug>[-\w\.]+)/$', TeamView.as_view(), name='scrum_team'),
    url(r'^t/(?P<slug>[-\w\.]+)/new/$', CreateSprintView.as_view(),
        name='scrum_sprint_new'),
    url(r'^p/(?P<slug>[-\w\.]+)/edit/$', EditProjectView.as_view(),
        name='scrum_project_edit'),
    url(r'^t/(?P<slug>[-\w\.]+)/edit/$', EditTeamView.as_view(),
        name='scrum_team_edit'),
    url(r'^p/(?P<slug>[-\w\.]+)/products/$', CreateBZProductView.as_view(),
        name='scrum_project_products'),
    url(r'^p/(?P<slug>[-\w\.]+)/bugs/$', ManageProjectBugsView.as_view(),
        name='scrum_project_bugs'),
    url(r'^p/(?P<slug>[-\w\.]+)/backlog/$', ProjectBacklogView.as_view(),
        name='scrum_project_backlog'),
    url(r'^t/(?P<slug>[-\w\.]+)/(?P<sslug>[-\w\.]+)/$', SprintView.as_view(),
        name='scrum_sprint'),
    url(r'^t/(?P<slug>[-\w\.]+)/(?P<sslug>[-\w\.]+)/edit/$',
        EditSprintView.as_view(), name='scrum_sprint_edit'),
    url(r'^t/(?P<slug>[-\w\.]+)/(?P<sslug>[-\w\.]+)/bugs/$',
        ManageSprintBugsView.as_view(), name='scrum_sprint_bugs'),
    url(r'^projects/(?P<path>.*)', RedirectOldURLsView.as_view()),
    url(r'^bugs_updated/$', CheckRecentUpdates.as_view(),
        name='scrum_bugs_updated'),
)

urls.py
from django.conf import settings
from django.conf.urls import *  # noqa
from django.contrib import admin
from django.views.generic import TemplateView

import jingo.monkey

admin.autodiscover()

handler500 = 'scrum.views.server_error'

urlpatterns = patterns('',
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^help/', TemplateView.as_view(template_name='help.html'),
        name='help'),
    url(r'^$', 'scrum.views.home', name='scrum_home'),
    url(r'^bugzilla/', include('bugzilla.urls')),
    url(r'^bugmail/', include('bugmail.urls')),
    url(r'', include('scrum.urls')),
    url(r'', include('django_browserid.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^500/$', handler500),
        (r'^404/$', handler404),
    )


# Monkeypatches!
# Patch Django to support __html__ for rendering in Jinja.
jingo.monkey.patch()

scrum/forms.py
from django.core.exceptions import ValidationError
from django.core.validators import validate_comma_separated_integer_list

import floppyforms as forms

from scrum.models import Project, Sprint, Team, BZProduct


date5 = forms.DateInput(attrs={
    'placeholder': 'YYYY-MM-DD',
})


class SlugInput(forms.TextInput):

    def get_context_data(self):
        self.attrs['pattern'] = "[-.\w]+"
        return super(SlugInput, self).get_context_data()


class ProjectForm(forms.ModelForm):
    template_title = 'Project'

    class Meta:
        model = Project
        widgets = {
            'slug': SlugInput,
        }
        fields = (
            'name',
            'slug',
            'team',
        )


class CreateProjectForm(ProjectForm):
    """Form for creating new projects."""
    product = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': 'Bugzilla Product/Component',
        }),
        help_text=('Select the "__ALL__" component '
                   'to include the entire Product.'),
    )

    def clean_product(self):
        prod = self.cleaned_data['product']
        if prod and '/' not in prod:
            raise ValidationError('Must be in the form "product/component"')
        return prod

    def save(self, commit=True):
        obj = super(CreateProjectForm, self).save(commit)
        if commit:
            self.add_product(obj)
        return obj

    def add_product(self, obj):
        prod = self.cleaned_data['product']
        if prod:
            prod, comp = prod.split('/', 1)
            obj.products.create(name=prod, component=comp, project=obj)


class SprintForm(forms.ModelForm):
    template_title = 'Sprint'

    class Meta:
        model = Sprint
        widgets = {
            'name': forms.TextInput,
            'slug': SlugInput,
            'start_date': date5,
            'end_date': date5,
            'notes': forms.Textarea(attrs={
                'class': 'span5',
            }),
        }
        fields = (
            'name',
            'slug',
            'start_date',
            'end_date',
            'notes',
            'team',
        )


class TeamForm(forms.ModelForm):

    class Meta:
        model = Team
        fields = (
            'name',
            'slug',
        )


class SprintBugsForm(forms.ModelForm):
    add_bugs = forms.CharField(
        required=False,
        widget=forms.HiddenInput,
        validators=[validate_comma_separated_integer_list],
    )
    remove_bugs = forms.CharField(
        required=False,
        widget=forms.HiddenInput,
        validators=[validate_comma_separated_integer_list],
    )

    class Meta:
        model = Sprint
        fields = ('add_bugs', 'remove_bugs')

    def _clean_bugs_list(self, field_name):
        bugs = self.cleaned_data[field_name]
        bugs_list = []
        if bugs:
            bugs_list = [int(b) for b in bugs.split(',')]
        return bugs_list

    def clean_add_bugs(self):
        return self._clean_bugs_list('add_bugs')

    def clean_remove_bugs(self):
        return self._clean_bugs_list('remove_bugs')

    def save(self, commit=True):
        add_bugs = self.cleaned_data['add_bugs']
        remove_bugs = self.cleaned_data['remove_bugs']
        self.instance.update_bugs(add_bugs, remove_bugs)
        self.instance._clear_bugs_data_cache()
        return self.instance


class ProjectBugsForm(SprintBugsForm):
    class Meta:
        model = Project
        fields = ('add_bugs', 'remove_bugs')


class CreateTeamForm(forms.ModelForm):

    class Meta:
        model = Team
        fields = (
            'name',
            'slug',
        )


class BZProductForm(forms.ModelForm):

    class Meta:
        model = BZProduct
        fields = (
            'name',
            'component',
            'project',
        )

scrum/views.py
import json
import logging
from datetime import date

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.validators import validate_comma_separated_integer_list
from django.http import (Http404, HttpResponse, HttpResponseBadRequest,
                         HttpResponseForbidden, HttpResponsePermanentRedirect)
from django.shortcuts import get_object_or_404, redirect, render
from django.template.context import Context
from django.views.generic import (CreateView, DeleteView, DetailView,
                                  ListView, TemplateView, UpdateView, View)

import celery

from bugzilla.api import bugzilla
from scrum.forms import (CreateProjectForm, CreateTeamForm, BZProductForm,
                         ProjectBugsForm, ProjectForm, SprintBugsForm,
                         SprintForm, TeamForm)
from scrum.models import BZProduct, Project, Sprint, Team, Bug, store_bugs


redis_client = None
if getattr(settings, 'BROKER_URL', '').startswith('redis:'):
    redis_client = celery.current_app.backend.client
log = logging.getLogger(__name__)


class ProtectedCreateView(CreateView):
    def dispatch(self, request, *args, **kwargs):
        @permission_required('%s.add_%s' % (self.model._meta.app_label,
                                            self.model._meta.module_name))
        def wrap(request, *args, **kwargs):
            return super(ProtectedCreateView, self).dispatch(request,
                                                             *args, **kwargs)
        return wrap(request, *args, **kwargs)


class ProtectedUpdateView(UpdateView):
    def dispatch(self, request, *args, **kwargs):
        @permission_required('%s.change_%s' % (self.model._meta.app_label,
                                               self.model._meta.module_name))
        def wrap(request, *args, **kwargs):
            return super(ProtectedUpdateView, self).dispatch(request,
                                                             *args, **kwargs)
        return wrap(request, *args, **kwargs)


class ProtectedDeleteView(DeleteView):
    def dispatch(self, request, *args, **kwargs):
        @permission_required('%s.delete_%s' % (self.model._meta.app_label,
                                               self.model._meta.module_name))
        def wrap(request, *args, **kwargs):
            return super(ProtectedDeleteView, self).dispatch(request,
                                                             *args, **kwargs)
        return wrap(request, *args, **kwargs)


class BugsDataMixin(object):
    def get_bugs_context(self, context, kwargs, bugs=None):
        scrum_only = kwargs.pop('scrum_only', True)
        self.bugs_kwargs = {'scrum_only': scrum_only}
        # clear cache if requested
        if self.request.META.get('HTTP_CACHE_CONTROL') == 'no-cache':
            self.bugs_kwargs['refresh'] = True
            messages.info(self.request, "The bugs will be refreshed from "
                                        "Bugzilla in a minute or two.")
        if 'all' in self.request.GET:
            self.bugs_kwargs['scrum_only'] = False
        context['scrum_only'] = self.bugs_kwargs.get('scrum_only', scrum_only)
        context['refresh'] = self.bugs_kwargs.get('refresh', False)
        if bugs is not None:
            self.bugs_kwargs['bugs'] = bugs
        bugs = self.object.get_bugs(**self.bugs_kwargs)
        context['blocked_bugs'] = bugs.get_blocked()
        context['flagged_bugs'] = bugs.get_flagged()
        context['bugs'] = bugs
        context['bz_search_url'] = bugs.get_bz_search_url()
        context['bugs_data'] = bugs.get_graph_data()
        context['bugs_data_json'] = json.dumps(context['bugs_data'])

    def get_context_data(self, **kwargs):
        context = super(BugsDataMixin, self).get_context_data(**kwargs)
        self.get_bugs_context(context, kwargs)
        return context


class ProjectsMixin(object):
    model = Project

    def get_context_data(self, **kwargs):
        context = super(ProjectsMixin, self).get_context_data(**kwargs)
        if hasattr(self, 'project'):
            context['project'] = self.project
        return context


class HomeView(TemplateView):
    template_name = 'scrum/home.html'
home = HomeView.as_view()


class ProjectView(BugsDataMixin, ProjectsMixin, DetailView):
    template_name = 'scrum/project.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectView, self).get_context_data(**kwargs)
        today = date.today()
        bugs = Bug.objects.filter(sprint__start_date__lte=today,
                                  sprint__end_date__gte=today,
                                  project=self.object)
        context['sprinting'] = bugs
        context['sprinting_blocked'] = bugs.get_blocked()
        context['sprinting_flagged'] = bugs.get_flagged()
        return context


class ProjectBacklogView(BugsDataMixin, ProjectsMixin, DetailView):
    template_name = 'scrum/project_backlog.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectBacklogView, self).get_context_data(**kwargs)
        self.get_bugs_context(context, kwargs, self.object.get_backlog())
        return context


class TeamView(DetailView):
    model = Team
    template_name = 'scrum/team.html'


class ListTeamsView(ListView):
    model = Team
    template_name = 'scrum/teams_list.html'
    context_object_name = 'teams'


class CreateTeamView(ProtectedCreateView):
    model = Team
    form_class = CreateTeamForm
    template_name = 'scrum/team_form.html'


class ListProjectsView(ProjectsMixin, ListView):
    template_name = 'scrum/projects_list.html'
    context_object_name = 'projects'


class EditProjectMixin(object):
    def get_context_data(self, **kwargs):
        context = super(EditProjectMixin, self).get_context_data(**kwargs)
        bz_prod_choices = []
        for prod, comps in bugzilla.get_products_simplified().items():
            comps.insert(0, '__ALL__')
            for comp in comps:
                bz_prod_choices.append('%s :: %s' % (prod, comp))
        context['bz_product_choices'] = bz_prod_choices
        return context


class CreateProjectView(EditProjectMixin, ProjectsMixin, ProtectedCreateView):
    model = Project
    form_class = CreateProjectForm
    template_name = 'scrum/project_form.html'


class EditProjectView(EditProjectMixin, ProjectsMixin, ProtectedUpdateView):
    form_class = ProjectForm
    template_name = 'scrum/project_form.html'


class CreateSprintView(ProtectedCreateView):
    model = Sprint
    form_class = SprintForm
    template_name = 'scrum/sprint_form.html'

    def get_context_data(self, **kwargs):
        context = super(CreateSprintView, self).get_context_data(**kwargs)
        context['team'] = self.team
        return context

    def get_success_url(self):
        return reverse('scrum_sprint_bugs', args=[self.team.slug,
                                                  self.object.slug])

    def get_form_kwargs(self):
        kwargs = super(CreateSprintView, self).get_form_kwargs()
        if 'data' in kwargs:
            print kwargs['data']
            form_data = kwargs['data'].copy()
            form_data['team'] = self.team.id
            kwargs['data'] = form_data
        return kwargs

    def get_initial(self):
        self.team = get_object_or_404(Team, slug=self.kwargs['slug'])
        return super(CreateSprintView, self).get_initial()

    def form_valid(self, form):
        return super(CreateSprintView, self).form_valid(form)


class SprintMixin(object):
    model = Sprint
    context_object_name = 'sprint'

    def get_object(self, queryset=None):
        tslug = self.kwargs.get('slug')
        sslug = self.kwargs.get('sslug')
        sprint = get_object_or_404(Sprint, team__slug=tslug, slug=sslug)
        self.team = sprint.team
        return sprint

    def get_context_data(self, **kwargs):
        context = super(SprintMixin, self).get_context_data(**kwargs)
        context['team'] = self.team
        return context


class SprintView(BugsDataMixin, SprintMixin, DetailView):
    template_name = 'scrum/sprint.html'

    def get_context_data(self, **kwargs):
        context = super(SprintView, self).get_context_data(**kwargs)
        context['team'] = self.team
        context['bugs_data'].update(self.object.get_burndown_data())
        context['bugs_data_json'] = json.dumps(context['bugs_data'])
        return context


class EditSprintView(SprintMixin, ProtectedUpdateView):
    form_class = SprintForm
    template_name = 'scrum/sprint_form.html'

    def get_form_kwargs(self):
        kwargs = super(EditSprintView, self).get_form_kwargs()
        if 'data' in kwargs:
            form_data = kwargs['data'].copy()
            form_data['team'] = self.team.id
            kwargs['data'] = form_data
        return kwargs


class EditTeamView(ProtectedUpdateView):
    model = Team
    form_class = TeamForm
    template_name = 'scrum/team_form.html'


class ManageSprintBugsView(BugsDataMixin, SprintMixin, ProtectedUpdateView):
    form_class = SprintBugsForm
    template_name = 'scrum/sprint_bugs.html'

    def get_context_data(self, **kwargs):
        kwargs['scrum_only'] = False
        context = super(ManageSprintBugsView, self).get_context_data(**kwargs)
        bugs = self.team.get_bugs(**self.bugs_kwargs)
        context['backlog_bugs'] = bugs
        context['blocked_backlog_bugs'] = bugs.get_blocked()
        context['flagged_backlog_bugs'] = bugs.get_flagged()
        context['bugs_data'].update(self.object.get_burndown_data())
        context['bugs_data_json'] = json.dumps(context['bugs_data'])
        context['old_sprint_bugs'] = Bug.objects.filter(
            sprint__team=self.team,

scrum/templates/scrum/base_project.html
{% extends "scrum/base.html" %}
{% from "scrum/includes/macros.html" import left_nav %}

{% block title %}{{ project.name + " /" if project }} Projects / {{ super() }}{% endblock %}

{% block left_nav_list %}
  {{ left_nav('Projects', projects, project) }}
{% endblock %}

scrum/templates/scrum/base_team.html
{% extends "scrum/base.html" %}
{% from "scrum/includes/macros.html" import left_nav %}

{% block title %}{{ team.name + " /" if team }} Teams / {{ super() }}{% endblock %}

{% block left_nav_list %}
  {{ left_nav('Teams', teams, team) }}
{% endblock %}

scrum/templates/scrum/bug.html
{% extends "base.html" %}
{% from "scrum/includes/macros.html" import flags_markers, flags_links with context %}

{% block content %}
  <div class="row">
    <div class="span12">
      <a class="btn pull-right show-tooltip"
         href="#"
         title="Refresh data from Bugzilla"
         id="shift-refresh">
        <i class="icon-refresh"></i> Refresh Data
      </a>
      {% if bug %}
        <h1>Details for Bug <a class="show-tooltip" href="{{ bug.get_bugzilla_url() }}" title="Open in Bugzilla">{{ bug.id }}</a></h1>
        <table class="table table-striped table-hover table-bordered">
          <tr>
            <th>Summary</th>
            <td>{{ flags_markers( [bug.id], bug ) }}{{ bug.summary }}</td>
          </tr>
          <tr>
            <th>Last Modified</th>
            <td>{{ timeago(bug.last_change_time) }}</td>
          </tr>
          <tr>
            <th>Last Synced From Bugzilla</th>
            <td>{{ timeago(bug.last_synced_time) }}</td>
          </tr>
          <tr>
            <th>Status</th>
            <td>{{ bug.status }}{{ ' &ndash; '|safe if bug.resolution }}{{ bug.resolution }}</td>
          </tr>
          <tr>
            <th>Product</th>
            <td>{{ bug.product }}</td>
          </tr>
          <tr>
            <th>Component</th>
            <td>{{ bug.component }}</td>
          </tr>
          <tr>
            <th>Assigned To</th>
            <td>{{ bug.assigned_to }}</td>
          </tr>
          <tr>
            <th>Story User</th>
            <td>{{ bug.story_user }}</td>
          </tr>
          <tr>
            <th>Story Component</th>
            <td>{{ bug.story_comonent }}</td>
          </tr>
          <tr>
            <th>Story Points</th>
            <td>{{ bug.story_points }}</td>
          </tr>
          {% if bug.project %}
            <tr>
              <th>Project</th>
              <td><a href="{{ bug.project.get_absolute_url() }}">{{ bug.project }}</a></td>
            </tr>
          {% else %}
            <tr>
              <th><span class="show-tooltip" title="The project(s) in whose backlog(s) this bug shows.">Matching Projects (Backlogs)</span></th>
              <td>{{ project_links(bug) }}</td>
            </tr>
          {% endif %}
          {% if bug.sprint %}
            <tr>
              <th>Sprint</th>
              <td><a href="{{ bug.sprint.get_absolute_url() }}">{{ bug.sprint }}</a></td>
            </tr>
          {% endif %}
        </table>

        {% if bug.sprint_actions.all() %}
          <h2>Sprint History</h2>
          <table class="table table-striped table-hover table-bordered">
            <tr>
              <th>Action</th>
              <th>Sprint</th>
              <th>When</th>
            </tr>
            {% for log in bug.sprint_actions.all() %}
              <tr>
                <td class="bug-log-action">{{ log.get_action_display() }}&nbsp;{% if log.action == log.ADDED %}to{% else %}from{% endif %}</td>
                <td><a href="{{ log.sprint.get_absolute_url() }}">{{ log.sprint }}</a></td>
                <td>{{ timeago(log.timestamp) }}</td>
              </tr>
            {% endfor %}
          </table>
        {% endif %}
      {% else %}
        {% if tried_bugzilla %}
          <h1>Oh Noes! Bug Not Found!</h1>
          <p>We can't find the bug in the database or Bugzilla. Either the bug ID in the URL is invalid, or the bug is private and ScrumBugs lacks the permission to access it.</p>
          <p>Sorry about that.</p>
        {% else %}
          <h1>Say What?</h1>
          <p>That bug isn't in the database. Hit the "Refresh Data" button in the upper right (or just shift-refresh) and we'll try to grab the bug from Bugzilla.</p>
          <p>Thanks!</p>
        {% endif %}
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block js %}
  {% compressed_js 'bugs' %}
  <script type="text/javascript">
    $(function(){
        "use strict";
        $('time.timeago').timeago();
    });
  </script>
{% endblock %}

{% macro project_links(bug) -%}
  {% for project in bug.projects_from_product() -%}
    <a href="{{ project.get_absolute_url() }}">{{ project }}</a>{{ ', ' if not loop.last }}
  {%- else -%}
    None
  {%- endfor -%}
{% endmacro %}

{% macro timeago(timestamp) -%}
  <time class="timeago" datetime="{{ timestamp }}">{{ timestamp.strftime('%B %d, %Y at %I:%M %p %Z') }}</time>
{% endmacro %}

scrum/templates/scrum/bugs_table.html
{% from "scrum/includes/macros.html" import bug_table with context %}

<div class="row">
  <div class="span12">
    {% if not scrum_only %}
      <a href="{{ request.path }}" class="btn pull-right">Hide dataless bugs</a>
    {% endif %}
    <h2>Stories</h2>
    {% if scrum_only and object.num_no_data_bugs %}
      <div class="alert">
        <button class="close" data-dismiss="alert">&times;</button>
        <strong>Warning!</strong> There are {{ object.num_no_data_bugs }} bug{{ object.num_no_data_bugs|pluralize }} with no scrum data.
        <a href="?all=1">Show them</a>?
      </div>
    {% endif %}
    {{ bug_table(bugs, blocked_bugs=blocked_bugs, flagged_bugs=flagged_bugs) }}
  </div>
</div>

<div class="row">
    <div class="span12">
        {% if bz_search_url %}
            <a href="{{ bz_search_url }}" target="_blank" class="btn pull-right">See in Bugzilla</a>
        {% endif %}
        {% for product in object.get_products() %}
            <a class="btn" target="_blank" href="{{ BUGZILLA_FILE_URL }}product={{ product }}"><i class="icon-plus-sign"></i> {{ product }} bug</a>
        {% endfor %}
    </div>
</div>
<div class="row">
  <div class="span12">
    <h4>Legend</h4>
    <table class="table table-hover">
      <tbody>
      <tr class="success pull-left">
        <td>Closed</td>
      </tr>
      <tr class="warning pull-left">
        <td>Unassigned</td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="span12">
    <p><strong>NOTE:</strong> Hard (shift) refresh your browser to get new data from Bugzilla.</p>
  </div>
</div>

scrum/templates/scrum/bzproduct_form.html
<form action="{{ bzproduct_form_url }}"
      class="form-horizontal"
      method="post"
      autocomplete="off"
      id="bzproduct_form">
  {{ csrf() }}
  <div class="control-group">
    <label class="control-label" for="id_product">Add a Product</label>
    <div class="controls">
      <div class="input" id="id_url_wrapper">
        <select name="product" id="id_product" class="input-xxlarge"
                data-placeholder="Bugzilla Product :: Component">
          <option value=""></option>
          {% for bzproduct in bz_product_choices %}
            <option value="{{ bzproduct }}">{{ bzproduct }}</option>
          {% endfor %}
        </select>
        <button class="btn" type="submit" id="add_product_btn"><i class="icon-plus" id="add_product_icon"></i></button>
        <p class="help-block">Select the "__ALL__" component to include the entire Product.</p>
      </div>
    </div>
  </div>
</form>

scrum/templates/scrum/bzproduct_list.html
<table class="table table-striped table-condensed" id="bzproduct_list">
  <thead>
    <tr>
      <th>Product</th>
      <th>Component</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for product in bzproducts %}
      <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.component|d('__ALL__', True) }}</td>
        <td width="1">
          <a href="{{ url('scrum_product_delete', product.pk) }}" class="btn btn-mini btn-danger bzproduct-remove" title="Remove Product"><i class="icon-remove icon-white"></i></a>
        </td>
      </tr>
    {% else %}
      <tr>
        <td colspan="5">No Products so far</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

scrum/templates/scrum/modal_form.html
{% load bootstrap %}
<div class="modal hide fade" id="modal_form">
  <div class="modal-header">
    <a class="close" href="#" data-dismiss="modal">&times;</a>
    <h3>{{ "Update" if object else "New" }} {{ form.template_title }}</h3>
  </div>
  <form action="{{ request.get_full_path() }}"
        class="form-horizontal modal-form"
        method="post">
    {{ csrf() }}
    <div class="modal-body">
      {{ form|bootstrap }}
    </div>
    <div class="modal-footer">
      <button class="btn btn-primary" type="submit">{{ "Update" if object else "Create" }}</button>
      <button class="btn" data-dismiss="modal">Cancel</button>
    </div>
  </form>
</div>

scrum/templates/scrum/project.html
{% extends "scrum/base_project.html" %}
{% from "scrum/includes/macros.html" import bug_table with context %}

{% block content %}
  <div class="row">
    <div class="span12">
      {% if perms.scrum.change_project %}
        <a class="btn btn-primary pull-right"
           href="{{ url('scrum_project_edit', project.slug) }}">
          <i class="icon-edit icon-white"></i> Edit
        </a>
      {% endif %}
      <div class="page-header">
        <h1>{{ project.name }}
          <small>Part of the <a href="{{ project.team.get_absolute_url() }}">{{ project.team.name }}</a> team.</small>
        </h1>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <h2>Currently Sprinting</h2>
      {{ bug_table(sprinting, show_sprint=True, show_project=False, blocked_bugs=sprinting_blocked, flagged_bugs=sprinting_flagged) }}
      <hr>
      {% if perms.scrum.change_project %}
        <a class="btn btn-small btn-primary pull-right"
           href="{{ url('scrum_project_bugs', project.slug) }}">
          <i class="icon-list icon-white"></i> Manage Ready Stories
        </a>
      {% endif %}
      <a class="btn btn-small pull-right" href="{{ url('scrum_project_backlog', project.slug) }}">
        <i class="icon-list"></i> Full Backlog
      </a>
      <h2>Sprint Ready</h2>
      {{ bug_table(bugs, 'backlog_table', show_project=False, blocked_bugs=blocked_bugs, flagged_bugs=flagged_bugs) }}
    </div>
  </div>
{% endblock %}

{% block js %}
  {% compressed_js 'teams' %}
{% endblock %}

scrum/templates/scrum/storylist_item.html
<li id="{{ bug.id }}" data-id="{{ bug.id }}" data-points="{{ bug.story_points }}">
  <a href="{{ bug.get_absolute_url }}">{{ bug.id }}</a> &ndash; 
  <span class="story_points">{{ bug.story_points }}</span> &ndash; {{ bug.summary }}  
</li>